### ISSUE TITLE
unknown config key "profilemode"

### ISSUE THREAD

**Issue by max-holo** [xyming108/sulv-hugo-papermod#9]
windows下hugo最新版本 v0.115，在项目目录下启动hugo server -D
提示unknown config key "profilemode"

**Comment by JackrayWang** [comment]
一样的问题呀。。 求解

**Comment by xyming108** [comment]
把
```yaml
languages:
  en:
    languageName: "English"
    weight: 1
```
换成
```yaml
languages:
  en:
    params:
      languageName: "English"
      weight: 1
```
